# Generated by Django 4.2.3 on 2023-07-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoria', 'verbose_name_plural': 'historical Categorias'},
        ),
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicador de Oferta', 'verbose_name_plural': 'historical Indicadores de Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicador de Oferta', 'verbose_name_plural': 'Indicadores de Ofertas'},
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='discount_value',
            new_name='descount_value',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='discount_value',
            new_name='descount_value',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Indicador de Oferta'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Indicador de Oferta'),
        ),
    ]
